Repository IIM-Creative-Technology/node-js-socket.io-IIM-A4-DW2-Stark, pull requests merged in 2022-04, with the labels that each got.

#3 [nodemon] install nodemon + change start script
  package-lock.json
  package.json
Labels: Done

#8 [Prettier] init Prettier
  package-lock.json
  package.json
Labels: Done

#4 [Routing] Feature user routes
  index.js
  package-lock.json
  package.json
  routes/user.js
Labels: Done

#5 [Unit Test] Feature init jest
  README.md
  package-lock.json
  package.json
  sum.js
  tests/sum.test.js
Labels: Done

#6 [DATABASE] Enable database connection
  README.md
  index.js
  package-lock.json
  package.json
Labels: Done

#12 [Refactoring] Refactoring base code
  app.js
  app/app.js
  app/controllers/userController.js
  app/routes/user.js
  app/services/prisma.js
  assets/template/html/index.html
  package.json
  routes/user.js
Labels: Done, chore

#17 ADD socketIo config
  app/app.js
  app/socketio/index.html
  assets/template/html/index.html
  package-lock.json
  package.json
Labels: feature

#19 Setup chat
  README.md
  app/app.js
  app/index.js
  app/socketio/index.html
  package.json
Labels: feature
